site_name: Compclasses
site_description: Like *dataclasses*, but for composition
site_url: https://fbruzzesi.github.io/compclasses/
theme:
  name: material
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  logo: img/compclass-logo.svg
  favicon: img/compclass-logo.svg
  language: en
repo_name: FBruzzesi/compclasses
repo_url: https://github.com/fbruzzesi/compclasses
edit_uri: ''
plugins:
- search
- mkdocstrings
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
  - Compclasses: index.md
  - Getting Started: getting_started.md
  - Beyond The Basics: beyond_basics.md
  - API:
    - compclass: api/compclass.md
    - delegatee: api/delegatee.md
