site_name: Compclasses
nav:
  - Home: index.md
  # - Getting Started:
  - API:
    - compclass: api/compclass.md
    - delegatee: api/delegatee.md
plugins:
  - search
  - mkdocstrings
theme:
  name: material
  font:
    text: Ubuntu
    code: Ubuntu Mono
  feature:
    tabs: true
  palette:
    primary: white
    accent: blue
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
